

# This file was *autogenerated* from the file t_and_t_bar.sage
from sage.all_cmdline import *   # import sage library

_sage_const_100 = Integer(100); _sage_const_1 = Integer(1)
N=_sage_const_100 
PLOT_T=bar_chart([number_of_divisors(n) for n in range(_sage_const_1 ,N+_sage_const_1 )])
PLOT_T.save("t_plot.pdf")
PLOT_T_BAR=bar_chart([_sage_const_1 /n*sum([number_of_divisors(j) for j in range(_sage_const_1 ,n+_sage_const_1 )]) for n in range(_sage_const_1 ,N+_sage_const_1 )])
PLOT_T_BAR.save("t_bar_plot.pdf")

